CREATE DATABASE IF NOT EXISTS ALUMNOS;

USE ALUMNOS;

/*
TABLE STRUTURE FOR ALUMNOS
*/

DROP TABLE IF EXISTS ALUMNOS;
CREATE TABLE ALUMNOS(
 DNI VARCHAR(11) NOT NULL,
 NOMBRE VARCHAR(75) NOT NULL,
 CURSO VARCHAR(9) NOT NULL,
 CONSTRAINT PK_ALUMNOS
  PRIMARY KEY  (DNI)
);

/*
TABLE DATA FOR ALUMNOS.ALUMNOS
*/

INSERT INTO ALUMNOS   VALUES ('1','Luis Primero Primero','2003-2004') , 
                             ('2','Juan Segundo Segundo','2003-2004') ;
